# Generated by Django 3.2.5 on 2021-08-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('texto', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('respeto', models.IntegerField()),
                ('alimento', models.IntegerField()),
                ('dinero', models.IntegerField()),
                ('energia', models.IntegerField()),
                ('dopamina', models.IntegerField()),
                ('sueno', models.IntegerField()),
                ('supmoral', models.IntegerField()),
                ('soberbia', models.IntegerField()),
                ('gula', models.IntegerField()),
                ('avaricia', models.IntegerField()),
                ('ira', models.IntegerField()),
                ('lujuria', models.IntegerField()),
                ('pereza', models.IntegerField()),
                ('envidia', models.IntegerField()),
            ],
        ),
    ]
